var passport = require('passport');
//= PASSPORT_LOCAL_REQUIRE
//= PASSPORT_FACEBOOK_REQUIRE
//= PASSPORT_GOOGLE_REQUIRE
//= PASSPORT_TWITTER_REQUIRE
//= PASSPORT_VK_REQUIRE
//= PASSPORT_GITHUB_REQUIRE

//= PASSPORT_USER_MODEL
//= PASSPORT_SERIALIZER
//= PASSPORT_DESERIALIZER

//= PASSPORT_LOCAL_STRATEGY
//= PASSPORT_FACEBOOK_STRATEGY
//= PASSPORT_GOOGLE_STRATEGY
//= PASSPORT_TWITTER_STRATEGY
//= PASSPORT_VK_STRATEGY
//= PASSPORT_GITHUB_STRATEGY
