app.get('/login', user.loginGet);
app.post('/login', user.loginPost);
//app.get('/logout', userController.logout);
//app.get('/forgot', userController.getForgot);
//app.post('/forgot', userController.postForgot);
//app.get('/reset/:token', userController.getReset);
//app.post('/reset/:token', userController.postReset);
//app.get('/signup', userController.getSignup);
//app.post('/signup', userController.postSignup);
//app.get('/contact', contactController.getContact);
//app.post('/contact', contactController.postContact);
//app.get('/account', passportConf.isAuthenticated, userController.getAccount);
//app.post('/account/profile', passportConf.isAuthenticated, userController.postUpdateProfile);
//app.post('/account/password', passportConf.isAuthenticated, userController.postUpdatePassword);
//app.post('/account/delete', passportConf.isAuthenticated, userController.postDeleteAccount);
//app.get('/account/unlink/:provider', passportConf.isAuthenticated, userController.getOauthUnlink);
